# Generated by Django 5.1 on 2024-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='header_photo',
            field=models.ImageField(blank=True, default='profile_avatar.png', null=True, upload_to=''),
        ),
    ]
